apiVersion: v1
kind: ReplicationController
metadata:
  name: arun-rc
spec:
  replicas: 3
  selector:
    app: arun-rc
  template:
    metadata:
      labels:
        app: arun-rc
  spec:
    containers:
    - name: arun
      image: arunvel1988/arun-nodejs
      ports:
      - containerPort: 8080
